routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@indexoriginal')->name('index');

Route::get('/request','HomeController@frontForm')->name('frontForm');
Route::put('/request','HomeController@frontFormSubmit')->name('frontFormSubmit');
Route::get('/confirm/task/{task}/{client}','HomeController@confirmTask')->name('confirmTask');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::resource('dashboard','DashboardController');
    Route::resource('client','ClientController');
    Route::resource('user','UserController');
    Route::resource('task','TaskController');
    Route::resource('request','RequestController');
    Route::resource('category','CategoryController');

    Route::get('inspection/edit/{id}','InspectionController@edit')->name('inspection.edit');
    Route::put('inspection/{id}','InspectionController@update')->name('inspection.update');
    Route::get('inspection/sendToClient/{id}','InspectionController@sendToClient')->name('inspection.sendToClient');

    Route::get('request/{id}/{states}','RequestController@status')->name('request.status');

    Route::get('system/setting','SystemController@index')->name('system.setting');
    Route::post('system/setting','SystemController@update')->name('system.setting.update');
    Route::get('system/setting/mail','SystemController@mailTemplate')->name('system.setting.mail.index');
    Route::put('system/setting/mail','SystemController@mailTemplateUpdate')->name('system.setting.mail.update');
    Route::get('system/setting/homehtml','SystemController@homeHTML')->name('homeHTML');
    Route::put('system/setting/homehtml','SystemController@homeHTMLUpdate')->name('homeHTMLUpdate');



});



Route::group(['as' => 'staff.','prefix' => 'staff','namespace' => 'Staff','middleware' => ['auth','staff']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard.index');
    Route::get('task','TaskController@index')->name('task.index');
    Route::get('task/{task}','TaskController@show')->name('task.show');
    Route::put('/inspection/submit/{task}','InspectionController@submitForm')->name('inspection.submit');

});


Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function() {
    Route::get('profile/{id?}','ProfileController@index')->name('profile');
    Route::get('settings/{id?}','ProfileController@settings')->name('settings');
    Route::put('settings/{id?}','ProfileController@settingsUpdate')->name('settings.update');

});


Route::group(['middleware' => ['auth']],function() {
    Route::get('attachment/count/{id}','AttachmentController@attachmentCount')->name('attachment.count');

    Route::get('attachment/list/{id}','AttachmentController@getList')->name('attachment.list');
    Route::post('attachment/upload/{id}','AttachmentController@upload')->name('attachment.upload');
    Route::post('attachment/delete/{id}','AttachmentController@delete')->name('attachment.delete');
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['email'];
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Newsletter;

class ClientController extends Controller
{


    /* Client Index */
    public function index()
    {
        $clients                                     = Client::all();


        return response()->view('admin.client.index',compact('clients'));
    }




    /* Create Client */
    public function create()
    {
        return response()->view('admin.client.create');
    }



    /* Store Client */
    public function store(Request $request)
    {
        //Validation
        $this->validate($request,[
            'name'                                      => 'required|max:50',
            'email'                                     => 'email',
            'descriptions'                              => 'max:500'
        ]);

        //Store new client
        $client                                         = new Client();
        $client->name                                   = $request->name;
        $client->phone                                  = $request->phone;
        $client->email                                  = $request->email;
        $client->address                                = $request->address;
        $client->descriptions                           = $request->descriptions;
        $client->save();

        //MailChimp email store
        Newsletter::subscribeOrUpdate($client->email,[ 'NAME' => $client->name ]);


        return redirect()->route('admin.client.index')
                          ->with('status','New Client Added..')
        ;

    }



    /* Show Client */
    public function show($id)
    {
        //
    }




    /* Client Edit Page */
    public function edit($id)
    {
        $client                                          = Client::find($id);

      return response()->view('admin.client.edit',compact('client'));
    }




    /* Update Client Data */
    public function update(Request $request, $id)
    {
        //Validation
        $this->validate($request,[
            'name'                                           => 'required|max:50',
            'email'                                          => 'email',
            'descriptions'                                   => 'max:500'
        ]);

        //Save Client Data
        $client                                              = Client::find($id);
        $client->name                                        = $request->name;
        $client->email                                       = $request->email;
        $client->phone                                       = $request->phone;
        $client->address                                     = $request->address;
        $client->descriptions                                = $request->descriptions;
        $client->save();

        //Update MailChimp
        Newsletter::subscribeOrUpdate($client->email,[ 'NAME' => $client->name ]);

        return redirect()->back()
                          ->with('status','Client Data Successfully Updated..')
        ;
    }




    /* Delete Client */
    public function destroy($id)
    {
        $client                                               = Client::find($id);
        $client->delete();

        return redirect()->back()
                          ->with('status','Client Successfully Deleted.')
        ;
    }
}

resources/views/admin/client/create.blade.php
@extends('layouts.admin')

@section('title','Add Client')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">New Client</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.client.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email">
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="text" class="form-control" id="phone" name="phone">
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <textarea class="form-control" rows="1" name="address"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="address">Description</label>
                                <textarea class="form-control" rows="2" name="descriptions"></textarea>
                            </div>

                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.client.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@push('script')

@endpush

resources/views/admin/client/edit.blade.php
@extends('layouts.admin')

@section('title','Edit Client')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">New Client</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.client.update',$client->id)}}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{$client->name}}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{$client->email}}">
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="text" class="form-control" id="phone" name="phone" value="{{$client->phone}}">
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <textarea class="form-control" rows="1" name="address">{{$client->address}}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="address">Description</label>
                                <textarea class="form-control" rows="2" name="descriptions">{{$client->descriptions}}</textarea>
                            </div>

                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.client.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/client/index.blade.php
@extends('layouts.admin')

@section('title','Clients')

@push('css')

    <link href="{{asset('backend/'.'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">

@endpush


@section('content')
    <a href="{{route('admin.client.create')}}" class="btn btn-primary btn-success">Add Client</a>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">All Clients</h4>
                    <h6 class="card-subtitle"></h6>
                    <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered" width="100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Address</th>
                            <!--<th>Description</th>-->
                            <th>Added ON</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                @foreach($clients as $client)
                        <tr>
                            <td>{{$client->id}}</td>
                            <td>{{$client->name}}</td>
                            <td>{{$client->phone}}</td>
                            <td>{{$client->email}}</td>
                            <td>{{$client->address}}</td>
                            <!--<td>{{$client->descriptions}}</td>-->
                            <td>{{$client->created_at}}</td>
                            <td>
                                <a href="{{route('admin.client.edit',$client->id)}}"><i class="fas fa-edit"></i></a>
                                <a href="javascript:void(0)" class="delete-item" data-id="{{$client->id}}"><i class="fa fa-trash"></i> </a>
                            </td>
                        </tr>
                @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@push('script')
    <script src="{{asset('backend/'.'assets/extra-libs/DataTables/datatables.min.js')}}"></script>

    <script>
    $( document ).ready(function() {

    $("#datatable").DataTable({
        "order": [[ 5, "desc" ]],
        "columnDefs": [
            { "searchable": false, "targets": 5 }
        ]
    })

    $(".delete-item").click(function () {

        let deleteForm = document.createElement('form'),
            currentURL = `{{route('admin.client.destroy','deleteid')}}`,
            deleteURL = currentURL.replace('deleteid',this.dataset.id),
            csrfInput = document.createElement('input'),
            methodInput = document.createElement('input')
        deleteForm.style.display = 'none';
        deleteForm.method = 'POST'
        deleteForm.action = deleteURL
        csrfInput.name = `_token`
        csrfInput.value = `{{csrf_token()}}`
        methodInput.name = `_method`
        methodInput.value = `DELETE`
        deleteForm.appendChild(csrfInput)
        deleteForm.appendChild(methodInput)
        document.body.appendChild(deleteForm)
        deleteForm.submit()

    })


    })
</script>
@endpush

resources/views/admin/client/show.blade.php
@extends('layouts.admin')

@section('title','View Client')

@push('css')


@endpush


@section('content')
@endsection


@push('script')

@endpush