routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@indexoriginal')->name('index');

Route::get('/request','HomeController@frontForm')->name('frontForm');
Route::put('/request','HomeController@frontFormSubmit')->name('frontFormSubmit');
Route::get('/confirm/task/{task}/{client}','HomeController@confirmTask')->name('confirmTask');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::resource('dashboard','DashboardController');
    Route::resource('client','ClientController');
    Route::resource('user','UserController');
    Route::resource('task','TaskController');
    Route::resource('request','RequestController');
    Route::resource('category','CategoryController');

    Route::get('inspection/edit/{id}','InspectionController@edit')->name('inspection.edit');
    Route::put('inspection/{id}','InspectionController@update')->name('inspection.update');
    Route::get('inspection/sendToClient/{id}','InspectionController@sendToClient')->name('inspection.sendToClient');

    Route::get('request/{id}/{states}','RequestController@status')->name('request.status');

    Route::get('system/setting','SystemController@index')->name('system.setting');
    Route::post('system/setting','SystemController@update')->name('system.setting.update');
    Route::get('system/setting/mail','SystemController@mailTemplate')->name('system.setting.mail.index');
    Route::put('system/setting/mail','SystemController@mailTemplateUpdate')->name('system.setting.mail.update');
    Route::get('system/setting/homehtml','SystemController@homeHTML')->name('homeHTML');
    Route::put('system/setting/homehtml','SystemController@homeHTMLUpdate')->name('homeHTMLUpdate');



});



Route::group(['as' => 'staff.','prefix' => 'staff','namespace' => 'Staff','middleware' => ['auth','staff']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard.index');
    Route::get('task','TaskController@index')->name('task.index');
    Route::get('task/{task}','TaskController@show')->name('task.show');
    Route::put('/inspection/submit/{task}','InspectionController@submitForm')->name('inspection.submit');

});


Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function() {
    Route::get('profile/{id?}','ProfileController@index')->name('profile');
    Route::get('settings/{id?}','ProfileController@settings')->name('settings');
    Route::put('settings/{id?}','ProfileController@settingsUpdate')->name('settings.update');

});


Route::group(['middleware' => ['auth']],function() {
    Route::get('attachment/count/{id}','AttachmentController@attachmentCount')->name('attachment.count');

    Route::get('attachment/list/{id}','AttachmentController@getList')->name('attachment.list');
    Route::post('attachment/upload/{id}','AttachmentController@upload')->name('attachment.upload');
    Route::post('attachment/delete/{id}','AttachmentController@delete')->name('attachment.delete');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    public function Client(){
        return $this->belongsTo('App\Models\Client');
    }

    public function User(){
        return $this->belongsTo('App\User');
    }

    public function Status(){
        return $this->belongsTo('App\Models\Status');
    }

    public function Inspection(){
        return $this->hasOne('App\Models\Inspection','id','inspection_id');
    }

    public function Category(){
        return $this->hasOne('App\Models\Category','id','category_id');
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\MailSender;
use App\Laraption;
use App\Models\Category;
use App\Models\Client;
use App\Models\Notification;
use App\Models\Task;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();

        return response()->view('admin.task.index',compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();
        $users    = User::where('role_id',2)->get();
        $categories = Category::all();

      return response()->view('admin.task.create',compact('clients','users','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'description' => 'required',
            'client'      => 'required',
            'staff'       => 'required',
            'category'    => 'required',
            'address'     => 'required'
        ]);

        $task = new Task();
        $task->title = $request->title;
        $task->description = $request->description;
        $task->note     = $request->note;
        $task->address = $request->address;
        $task->client_id = $request->client;
        $task->category_id = $request->category;
        $task->user_id   = $request->staff;
        $task->save();

        /*Send Notification*/
        $this->sendToStaff('task',$task->id,$task->user_id,route('staff.task.show',$task->id),'New Task',$task->title);


        /*Send Email Notification*/
        $user = User::find($task->user_id);
        $mailb = Laraption::where('key','=','to.staff.task.assign.notification')->first();
        $mailb = json_decode($mailb ? $mailb->value : null);

        $mailRarray = [
            '#taskLink#' => route('staff.task.show',$task->id),
            '#taskTitle#' => $task->title,
            '#staff#'  => $user->name
        ];

        $mailbody = $mailb ? str_replace(array_keys($mailRarray),$mailRarray,$mailb->body) : '';
        $mailtitle = $mailb ? $mailb->title : 'You have new notification';

        $data = [
            'to' => $user->email,
            'name' => $user->name,
            'subject' => $mailtitle,
            'body' => $mailbody,
            'file'  => false
        ];
        MailSender::send('mail.task',$data);


        return redirect()->route('admin.task.index')->with('status','Task Successfully Submitted..');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        $inspection   = json_decode($task->Inspection->data??'');


        Notification::where('nof',$task->id)
            ->where('type','task')
            ->where('user_id',Auth::id())
            ->update([
                'read' => true
            ]);

        /*Attachment*/
        $attachment = (object) AttachmentController::attachmentC($task->id);

        return response()->view('admin.task.show',compact('task','inspection','attachment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::where('role_id',2)->get();
        $clients = Client::all();
        $task = Task::find($id);
        $categories = Category::all();

      return response()->view('admin.task.edit',compact('users','clients','task','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'description' => 'required',
            'client'      => 'required',
            'staff'       => 'required',
            'category'    => 'required',
            'address'    => 'required'
        ]);

        $task = Task::find($id);
        $task->title = $request->title;
        $task->description = $request->description;
        $task->note   = $request->note;
        $task->address = $request->address;
        $task->client_id = $request->client;
        $task->user_id   = $request->staff;
        $task->category_id = $request->category;
        $task->save();

        /*Send Notification*/
        if($task->status_id  == 1) {
            $this->sendToStaff('task',$task->id,$task->user_id,route('staff.task.show', $task->id),'Task Updated',$task->title);
        }


        /*Send Email Notification*/
        $user = User::find($task->user_id);
        $mailb = Laraption::where('key','=','to.staff.task.update.notification')->first();
        $mailb = json_decode($mailb ? $mailb->value : null);

        $mailRarray = [
            '#taskLink#' => route('staff.task.show',$task->id),
            '#taskTitle#' => $task->title,
            '#staff#'  => User::find($task->user_id)->name
        ];
        $mailbody = $mailb ? str_replace(array_keys($mailRarray),$mailRarray,$mailb->body) : '';
        $mailtitle = $mailb? $mailb->title : 'Your have received new notification.';

        $data = [
            'to' => $user->email,
            'name' => $user->name,
            'subject' => $mailtitle,
            'body' => $mailbody,
            'file'  => false
        ];

        MailSender::send('mail.task',$data);

        return redirect()->back()->with('status','Task Successfully Updated..');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function sendToStaff($type,$nof,$staff,$route,$title,$description){
        $notification = new Notification();
        $notification->type = $type;
        $notification->nof = $nof;
        $notification->user_id = $staff;
        $notification->route = $route;
        $notification->title = $title;
        $notification->description = $description;
        $notification->save();
    }
}

app/Http/Controllers/Staff/TaskController.php
<?php

namespace App\Http\Controllers\Staff;

use App\Models\Notification;
use App\Models\Task;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    public function index(){
        $tasks = Task::where('user_id',Auth::id())
                        ->get();

        return response()->view('staff.task.index',compact('tasks'));
    }

    public function show(Task $task){
        $inspection   = json_decode($task->Inspection->data??'');

        Notification::where('nof',$task->id)
            ->where('type','task')
            ->where('user_id',Auth::id())
            ->update([
                'read' => true
            ]);

        return response()->view('staff.task.show',compact('task','inspection'));
    }
}

resources/views/admin/task/create.blade.php
@extends('layouts.admin')

@section('title','Add Task')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">New Task</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.task.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" id="title" name="title">
                            </div>

                            <div class="form-group">
                                <label for="address">Property Address</label>
                                <input type="text" class="form-control" id="address" name="address">
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control" rows="2" name="description"></textarea>
                            </div>


                            <div class="form-group">
                                <label for="note">Note</label>
                                <textarea class="form-control" rows="2" name="note"></textarea>
                            </div>



                            <div class="form-group">
                                <label for="client">Client</label>
                                <select class="form-control select2-dropdown" name="client">
                                    @foreach($clients as $client)
                                        <option value="{{$client->id}}">{{$client->name}}</option>
                                        @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="staff">Staff</label>
                                <select class="form-control select2-dropdown" name="staff">
                                    @foreach($users as $user)
                                        <option value="{{$user->id}}">{{$user->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="staff">Category</label>
                                <select class="form-control select2-dropdown" name="category">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->title}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.task.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@push('script')

@endpush

resources/views/admin/task/edit.blade.php
@extends('layouts.admin')

@section('title','Edit Task')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">New Task</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.task.update',$task->id)}}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" id="title" name="title" value="{{$task->title}}">
                            </div>


                            <div class="form-group">
                                <label for="address">Property Address</label>
                                <input type="text" class="form-control" id="address" name="address" value="{{$task->address}}">
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control" rows="2" name="description">{{$task->description}}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="note">Note</label>
                                <textarea class="form-control" rows="2" name="note">{{$task->note}}</textarea>
                            </div>


                            <div class="form-group">
                                <label for="client">Client</label>
                                <select class="form-control select2-dropdown" name="client">
                                    @foreach($clients as $client)
                                        <option value="{{$client->id}}" {{$client->id == $task->client_id ? 'selected' : ''}}>{{$client->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="staff">Staff</label>
                                <select class="form-control select2-dropdown" name="staff">
                                    @foreach($users as $user)
                                        <option value="{{$user->id}}" {{$user->id == $task->user_id ? 'selected' : ''}}>{{$user->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="staff">Category</label>
                                <select class="form-control select2-dropdown" name="category">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}" {{$category->id == $task->category_id ? 'selected' : ''}}>{{$category->title}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.task.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/task/index.blade.php
@extends('layouts.admin')

@section('title','Task')

@push('css')
    <link href="{{asset('backend/'.'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">


@endpush


@section('content')
    <a href="{{route('admin.task.create')}}" class="btn btn-primary btn-success">Add Task</a>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">All Task</h4>
                    <h6 class="card-subtitle"></h6>
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped table-bordered" width="100%">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Client</th>
                                <th>Staff</th>
                                <th>Property Address</th>
                                <th>Status</th>
                                <th>Created at</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($tasks as $task)
                                <tr>
                                    <td>{{$task->id}}</td>
                                    <td>{{$task->title}}</td>
                                    <td>{{$task->Client->name??''}}</td>
                                    <td>{{$task->User->name??''}}</td>
                                    <td>{{$task->address}}</td>
                                    <td class="text-center"><span class="{{$task->Status->class??''}}">{{$task->Status->title??''}}</span></td>
                                    <td>{{$task->created_at}}</td>
                                    <td>
                                        <a href="{{route('admin.task.show',$task->id)}}"><i class="fa fa-eye"></i></a>
                                        <a href="{{route('admin.task.edit',$task->id)}}"><i class="fas fa-edit"></i></a>
                                        <a href="javascript:void(0)" class="delete-item" data-id="{{$task->id}}"><i class="fa fa-trash"></i> </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')
    <script src="{{asset('backend/'.'assets/extra-libs/DataTables/datatables.min.js')}}"></script>
    <script>
        $( document ).ready(function() {

            $("#datatable").DataTable({
                "order": [[ 6, "desc" ]],
                "columnDefs": [
                    { "searchable": false, "targets": 6 }
                ]
            })
        })
    </script>
@endpush

resources/views/admin/task/show.blade.php
@extends('layouts.admin')

@section('title','View Task')

@push('css')


@endpush


@section('content')
    <a href="{{route('admin.task.edit',$task->id)}}" class="btn btn-primary btn-success">Edit</a>
    <a href="{{route('admin.task.index')}}" class="btn btn-primary btn-dark">Back</a>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Task</h4>
                    <h6 class="card-subtitle"></h6>
                    <div class="r-separator">
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">ID : </span> {{$task->id}}</div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Title : </span> {{$task->title}}</div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Description : </span> {{$task->description}}</div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Client : </span> {{$task->Client->name??''}}</div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Staff : </span> {{$task->User->name??''}}</div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Status : </span> <span class="{{$task->Status->class??''}}">{{$task->Status->title??''}}</span></div>
                        <div class="row border-bottom p-3"><span class="mr-3 font-weight-bold">Note : </span> {{$task->note}}</div>

                    </div>
                </div>
            </div>
        </div>
    </div>


    @if($inspection)

        @includeIf('admin.inspection.show.'.$task->category_id)
        @includeWhen(!View::exists('admin.inspection.show.'.$task->category_id),'admin.inspection.show.default')

    @endif


@endsection


@push('script')
    @include('public.gallery')
@endpush