routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@indexoriginal')->name('index');

Route::get('/request','HomeController@frontForm')->name('frontForm');
Route::put('/request','HomeController@frontFormSubmit')->name('frontFormSubmit');
Route::get('/confirm/task/{task}/{client}','HomeController@confirmTask')->name('confirmTask');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::resource('dashboard','DashboardController');
    Route::resource('client','ClientController');
    Route::resource('user','UserController');
    Route::resource('task','TaskController');
    Route::resource('request','RequestController');
    Route::resource('category','CategoryController');

    Route::get('inspection/edit/{id}','InspectionController@edit')->name('inspection.edit');
    Route::put('inspection/{id}','InspectionController@update')->name('inspection.update');
    Route::get('inspection/sendToClient/{id}','InspectionController@sendToClient')->name('inspection.sendToClient');

    Route::get('request/{id}/{states}','RequestController@status')->name('request.status');

    Route::get('system/setting','SystemController@index')->name('system.setting');
    Route::post('system/setting','SystemController@update')->name('system.setting.update');
    Route::get('system/setting/mail','SystemController@mailTemplate')->name('system.setting.mail.index');
    Route::put('system/setting/mail','SystemController@mailTemplateUpdate')->name('system.setting.mail.update');
    Route::get('system/setting/homehtml','SystemController@homeHTML')->name('homeHTML');
    Route::put('system/setting/homehtml','SystemController@homeHTMLUpdate')->name('homeHTMLUpdate');



});



Route::group(['as' => 'staff.','prefix' => 'staff','namespace' => 'Staff','middleware' => ['auth','staff']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard.index');
    Route::get('task','TaskController@index')->name('task.index');
    Route::get('task/{task}','TaskController@show')->name('task.show');
    Route::put('/inspection/submit/{task}','InspectionController@submitForm')->name('inspection.submit');

});


Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function() {
    Route::get('profile/{id?}','ProfileController@index')->name('profile');
    Route::get('settings/{id?}','ProfileController@settings')->name('settings');
    Route::put('settings/{id?}','ProfileController@settingsUpdate')->name('settings.update');

});


Route::group(['middleware' => ['auth']],function() {
    Route::get('attachment/count/{id}','AttachmentController@attachmentCount')->name('attachment.count');

    Route::get('attachment/list/{id}','AttachmentController@getList')->name('attachment.list');
    Route::post('attachment/upload/{id}','AttachmentController@upload')->name('attachment.upload');
    Route::post('attachment/delete/{id}','AttachmentController@delete')->name('attachment.delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Role(){
        return $this->belongsTo('App\Role');
    }

    public function Notification(){
        return $this->hasMany('App\Models\Notification')->where('read',false);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\MailSender;
use App\Laraption;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

     return response()->view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

     return response()->view('admin.user.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|min:5|max:50',
            'email' => 'required|email|unique:users,email',
            'role'  => 'required',
            'password' => 'required|string|min:6|confirmed'
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->role_id = $request->role;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();

        $this->emailinfo($request,$user);

        return redirect()->route('admin.user.index')->with('status','New User Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::all();
        $user = User::find($id);

     return response()->view('admin.user.edit',compact('roles','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request,[
            'name' => 'required|min:5|max:50',
            'email' => 'required|email|unique:users,email,'.$id,
            'role'  => 'required'
        ]);

        if($request->password){
            $this->validate($request,[
                'password' => 'string|min:6|confirmed'
            ]);
        }
        $user = User::find($id);
        $emailinfo = ($request->email != $user->email) || ($request->password);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role_id = $request->role;
        if($request->password) {
            $user->password = Hash::make($request->password);
        }
        $user->save();

        if($emailinfo){
            $this->emailinfo($request,$user);
        }

        return redirect()->back()->with('status','User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->back()->with('status','User Successfully Deleted.');
    }


    private function emailinfo($request,$user){
        $mailb = Laraption::where('key','=','to.user.accountinfo')->first();
        $mailb = json_decode($mailb ? $mailb->value : null);

        $mailRarray = [
            '#user#' => $user->name,
            '#email#' => $user->email,
            '#password#'  => $request->password??''
        ];

        $mailbody = $mailb ? str_replace(array_keys($mailRarray),$mailRarray,$mailb->body) : '';
        $mailtitle = $mailb? $mailb->title : 'Your account information.';

        $data = [
            'to' => $user->email,
            'name' => $user->name,
            'subject' => $mailtitle,
            'body' => $mailbody,
            'file'  => false
        ];

        MailSender::send('mail.task',$data);
    }
}

app/Http/Controllers/User/ProfileController.php
<?php

namespace App\Http\Controllers\User;

use App\Laraption;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProfileController extends Controller
{

    private $user;

    private function getuser($id = false)
    {
        $user = Auth::user();
        if(($id && $user->id == $id) || (!$id)){
            $id = $user->id;
        }elseif (($user->role_id == 1) && ($id)){
            $id = $id;
        }else{
            abort(404);
        }

        $this->user = User::find($id);

        $confs = Laraption::where('key','REGEXP','user.id.'.$user->id)->get();
        foreach ($confs as $conf){
            Config::set('load.'.str_replace('.id.'.$user->id,'',$conf->key),$conf->value);
        }
    }

    public function index($id = false){
        $this->getuser($id);
        $user = $this->user;

        return response()->view('user.profile.view',compact('user'));
    }

    public function edit($id = false){
        $this->getuser($id);
        $user = $this->user;
        return response()->view('user.profile.settings',compact('user'));
    }

    public function update(Request $request,$id = false){

    }

    public function settings($id = false){
        $this->getuser($id);
        $user = $this->user;
        return response()->view('user.profile.settings',compact('user'));
    }

    public function settingsUpdate(Request $request,$id){

            $this->validate($request,[
                'name' => 'required|max:50',
                'email' => 'required|email|unique:users,email,'.$id,
                'image' => 'mimes:jpg,jpeg,png,bmp,gif'
            ]);

            if($request->password){
                $this->validate($request,[
                    'password' => 'string|min:6|confirmed'
                    ]);
            }

        $this->getuser($id);
        $user = $this->user;
        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password){
        $user->password = Hash::make($request->password);
        }
        $user->save();

        $phone = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.phone'
        ]);
        $phone->value = $request->phone;
        $phone->save();


        $address = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.address'
        ]);
        $address->value = $request->address;
        $address->save();



        $image = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.image'
        ]);
        $imagefile = $request->file('image');
        $dir = 'profile';
        $imagename = $image->value;

        if(is_file($imagefile)){

            if (!Storage::disk('public')->exists($dir)) {
                Storage::disk('public')->makeDirectory($dir);
            }

            if(Storage::disk('public')->exists(str_replace('storage/','',$image->value))){
                Storage::disk('public')->delete(str_replace('storage/','',$image->value));
            }
            $imagename = uniqid().'.'.$imagefile->getClientOriginalExtension();
            $userImage = Image::make($imagefile)->resize(300,300)->save('storage/'.$dir.'/tmp.'.$imagefile->getClientOriginalExtension());
            Storage::disk('public')->put($dir.'/'.$imagename,$userImage);

            $imagename = 'storage/'.$dir.'/'.$imagename;

        }
        $image->value = $imagename;
        $image->save();


        return redirect()->back()->with('status','Settings Successfully Updated.');
    }
}

resources/views/layouts/partials/user/notice.blade.php
<script src="{{asset('backend/'.'assets/libs/toastr/build/toastr.min.js')}}"></script>
<script>
    $(function() {
        @if ($errors->any())
        @foreach ($errors->all() as $error)
        toastr.error(`{{$error}}`, 'Error!');
        @endforeach
        @endif
        @if (session('status'))
        toastr.success(`{{ session('status') }}`, 'Success');
        @endif
    })
</script>

resources/views/layouts/partials/user/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">

                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark" href="{{Auth::user()->role_id == 1 ? route('admin.dashboard.index') : route('staff.dashboard.index')}}" aria-expanded="false">
                        <i class="mdi mdi-av-timer"></i>
                        <span class="hide-menu">Dashboard </span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark" href="{{route('user.profile')}}" aria-expanded="false">
                        <i class="mdi mdi-av-timer"></i>
                        <span class="hide-menu">Profile </span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark" href="{{route('user.settings')}}" aria-expanded="false">
                        <i class="mdi mdi-av-timer"></i>
                        <span class="hide-menu">Settings </span>
                    </a>
                </li>


            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

resources/views/layouts/partials/user/topbar.blade.php
@php
    $notifications = Auth::user()->Notification??false;
    $countNotification = $notifications->count();
@endphp
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                <i class="ti-menu ti-close"></i>
            </a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <div class="navbar-brand">
                <a href="{{route('index')}}" class="logo">
                    <!-- Logo icon -->
                    <b class="logo-icon">
                        <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                        <!-- Light Logo icon -->
                        <img src="{{asset(Config::get('site.logo'))}}" alt="" class="light-logo" style="max-width: 220px;max-height: 55px" />
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        <!-- Light Logo text -->
                               <!-- <img src="../../assets/images/logo-light-text.png" class="light-logo" alt="homepage" />-->
                    </span>
                </a>
                <a class="sidebartoggler d-none d-md-block" href="javascript:void(0)" data-sidebartype="mini-sidebar">
                    <i class="mdi mdi-toggle-switch mdi-toggle-switch-off font-20"></i>
                </a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent"
               aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="ti-more"></i>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav float-left mr-auto">
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown border-right">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="mdi mdi-bell-outline font-22"></i>
                        <span class="badge badge-pill badge-info noti">{{$countNotification}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown">
                                <span class="with-arrow">
                                    <span class="bg-primary"></span>
                                </span>
                        <ul class="list-style-none">
                            <li>
                                <div class="drop-title bg-primary text-white">
                                    <h4 class="mb-0 m-t-5">{{$countNotification}} New</h4>
                                    <span class="font-light">Notifications</span>
                                </div>
                            </li>
                            <li>
                                <div class="message-center notifications">
                                    <!-- Message -->
                                    @if(!$countNotification)
                                        <div class="text-center">No notification.</div>
                                    @endif

                                    @foreach($notifications as $notification)
                                        <a href="{{$notification->route}}" class="message-item">
                                                <span class="btn btn-danger btn-circle">
                                                    <i class="fa fa-link"></i>
                                                </span>
                                            <div class="mail-contnet">
                                                <h5 class="message-title">{{$notification->title}}</h5>
                                                <span class="mail-desc">{{$notification->description}}</span>
                                                <span class="time">{{$notification->created_at}}</span>
                                            </div>
                                        </a>
                                @endforeach
                                    <!-- Message -->
                                </div>
                            </li>
                            <li>
                                <a class="nav-link text-center m-b-5" href="javascript:void(0);">
                                    <strong>Check all notifications</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{{asset(Config::get('user.image'))}}" alt="" class="rounded-circle" width="40">
                        <span class="m-l-5 font-medium d-none d-sm-inline-block">{{Auth::user()->name}} <i class="mdi mdi-chevron-down"></i></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                                <span class="with-arrow">
                                    <span class="bg-primary"></span>
                                </span>
                        <div class="d-flex no-block align-items-center p-15 bg-primary text-white m-b-10">
                            <div class="">
                                <img src="{{asset(Config::get('user.image'))}}" alt="" class="rounded-circle" width="60">
                            </div>
                            <div class="m-l-10">
                                <h4 class="mb-0">{{Auth::user()->name}}</h4>
                                <p class=" mb-0">{{Auth::user()->email}}</p>
                            </div>
                        </div>
                        <a class="dropdown-item" href="{{route('user.profile')}}">
                            <i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)">
                            <i class="ti-email m-r-5 m-l-5"></i> Inbox</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{route('user.settings')}}">
                            <i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" id="logout-link" href="javascript:void(0)">
                            <i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                        <div class="dropdown-divider"></div>
                        <div class="p-l-30 p-10">
                            <a href="{{route('user.profile')}}" class="btn btn-sm btn-success btn-rounded">View Profile</a>
                        </div>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>