routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@indexoriginal')->name('index');

Route::get('/request','HomeController@frontForm')->name('frontForm');
Route::put('/request','HomeController@frontFormSubmit')->name('frontFormSubmit');
Route::get('/confirm/task/{task}/{client}','HomeController@confirmTask')->name('confirmTask');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::resource('dashboard','DashboardController');
    Route::resource('client','ClientController');
    Route::resource('user','UserController');
    Route::resource('task','TaskController');
    Route::resource('request','RequestController');
    Route::resource('category','CategoryController');

    Route::get('inspection/edit/{id}','InspectionController@edit')->name('inspection.edit');
    Route::put('inspection/{id}','InspectionController@update')->name('inspection.update');
    Route::get('inspection/sendToClient/{id}','InspectionController@sendToClient')->name('inspection.sendToClient');

    Route::get('request/{id}/{states}','RequestController@status')->name('request.status');

    Route::get('system/setting','SystemController@index')->name('system.setting');
    Route::post('system/setting','SystemController@update')->name('system.setting.update');
    Route::get('system/setting/mail','SystemController@mailTemplate')->name('system.setting.mail.index');
    Route::put('system/setting/mail','SystemController@mailTemplateUpdate')->name('system.setting.mail.update');
    Route::get('system/setting/homehtml','SystemController@homeHTML')->name('homeHTML');
    Route::put('system/setting/homehtml','SystemController@homeHTMLUpdate')->name('homeHTMLUpdate');



});



Route::group(['as' => 'staff.','prefix' => 'staff','namespace' => 'Staff','middleware' => ['auth','staff']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard.index');
    Route::get('task','TaskController@index')->name('task.index');
    Route::get('task/{task}','TaskController@show')->name('task.show');
    Route::put('/inspection/submit/{task}','InspectionController@submitForm')->name('inspection.submit');

});


Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function() {
    Route::get('profile/{id?}','ProfileController@index')->name('profile');
    Route::get('settings/{id?}','ProfileController@settings')->name('settings');
    Route::put('settings/{id?}','ProfileController@settingsUpdate')->name('settings.update');

});


Route::group(['middleware' => ['auth']],function() {
    Route::get('attachment/count/{id}','AttachmentController@attachmentCount')->name('attachment.count');

    Route::get('attachment/list/{id}','AttachmentController@getList')->name('attachment.list');
    Route::post('attachment/upload/{id}','AttachmentController@upload')->name('attachment.upload');
    Route::post('attachment/delete/{id}','AttachmentController@delete')->name('attachment.delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Role(){
        return $this->belongsTo('App\Role');
    }

    public function Notification(){
        return $this->hasMany('App\Models\Notification')->where('read',false);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\MailSender;
use App\Laraption;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

     return response()->view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

     return response()->view('admin.user.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|min:5|max:50',
            'email' => 'required|email|unique:users,email',
            'role'  => 'required',
            'password' => 'required|string|min:6|confirmed'
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->role_id = $request->role;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();

        $this->emailinfo($request,$user);

        return redirect()->route('admin.user.index')->with('status','New User Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::all();
        $user = User::find($id);

     return response()->view('admin.user.edit',compact('roles','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request,[
            'name' => 'required|min:5|max:50',
            'email' => 'required|email|unique:users,email,'.$id,
            'role'  => 'required'
        ]);

        if($request->password){
            $this->validate($request,[
                'password' => 'string|min:6|confirmed'
            ]);
        }
        $user = User::find($id);
        $emailinfo = ($request->email != $user->email) || ($request->password);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role_id = $request->role;
        if($request->password) {
            $user->password = Hash::make($request->password);
        }
        $user->save();

        if($emailinfo){
            $this->emailinfo($request,$user);
        }

        return redirect()->back()->with('status','User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->back()->with('status','User Successfully Deleted.');
    }


    private function emailinfo($request,$user){
        $mailb = Laraption::where('key','=','to.user.accountinfo')->first();
        $mailb = json_decode($mailb ? $mailb->value : null);

        $mailRarray = [
            '#user#' => $user->name,
            '#email#' => $user->email,
            '#password#'  => $request->password??''
        ];

        $mailbody = $mailb ? str_replace(array_keys($mailRarray),$mailRarray,$mailb->body) : '';
        $mailtitle = $mailb? $mailb->title : 'Your account information.';

        $data = [
            'to' => $user->email,
            'name' => $user->name,
            'subject' => $mailtitle,
            'body' => $mailbody,
            'file'  => false
        ];

        MailSender::send('mail.task',$data);
    }
}

app/Http/Controllers/User/ProfileController.php
<?php

namespace App\Http\Controllers\User;

use App\Laraption;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProfileController extends Controller
{

    private $user;

    private function getuser($id = false)
    {
        $user = Auth::user();
        if(($id && $user->id == $id) || (!$id)){
            $id = $user->id;
        }elseif (($user->role_id == 1) && ($id)){
            $id = $id;
        }else{
            abort(404);
        }

        $this->user = User::find($id);

        $confs = Laraption::where('key','REGEXP','user.id.'.$user->id)->get();
        foreach ($confs as $conf){
            Config::set('load.'.str_replace('.id.'.$user->id,'',$conf->key),$conf->value);
        }
    }

    public function index($id = false){
        $this->getuser($id);
        $user = $this->user;

        return response()->view('user.profile.view',compact('user'));
    }

    public function edit($id = false){
        $this->getuser($id);
        $user = $this->user;
        return response()->view('user.profile.settings',compact('user'));
    }

    public function update(Request $request,$id = false){

    }

    public function settings($id = false){
        $this->getuser($id);
        $user = $this->user;
        return response()->view('user.profile.settings',compact('user'));
    }

    public function settingsUpdate(Request $request,$id){

            $this->validate($request,[
                'name' => 'required|max:50',
                'email' => 'required|email|unique:users,email,'.$id,
                'image' => 'mimes:jpg,jpeg,png,bmp,gif'
            ]);

            if($request->password){
                $this->validate($request,[
                    'password' => 'string|min:6|confirmed'
                    ]);
            }

        $this->getuser($id);
        $user = $this->user;
        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password){
        $user->password = Hash::make($request->password);
        }
        $user->save();

        $phone = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.phone'
        ]);
        $phone->value = $request->phone;
        $phone->save();


        $address = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.address'
        ]);
        $address->value = $request->address;
        $address->save();



        $image = Laraption::firstOrNew([
            'key' => 'user.id.'.$id.'.image'
        ]);
        $imagefile = $request->file('image');
        $dir = 'profile';
        $imagename = $image->value;

        if(is_file($imagefile)){

            if (!Storage::disk('public')->exists($dir)) {
                Storage::disk('public')->makeDirectory($dir);
            }

            if(Storage::disk('public')->exists(str_replace('storage/','',$image->value))){
                Storage::disk('public')->delete(str_replace('storage/','',$image->value));
            }
            $imagename = uniqid().'.'.$imagefile->getClientOriginalExtension();
            $userImage = Image::make($imagefile)->resize(300,300)->save('storage/'.$dir.'/tmp.'.$imagefile->getClientOriginalExtension());
            Storage::disk('public')->put($dir.'/'.$imagename,$userImage);

            $imagename = 'storage/'.$dir.'/'.$imagename;

        }
        $image->value = $imagename;
        $image->save();


        return redirect()->back()->with('status','Settings Successfully Updated.');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('title','Create User')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">New User</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.user.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email">
                            </div>

                            <div class="form-group">
                                <label for="role">Role</label>
                                <select class="select2 form-control" name="role">
                                    @foreach($roles as $role)
                                        <option value="{{$role->id}}" {{$role->id == 2 ? 'selected' : ''}}>{{$role->title}}</option>
                                    @endforeach
                                </select>
                            </div>


                            <div class="form-group">
                                <label for="phone">Password</label>
                                <input type="password" class="form-control" id="phone" name="password">
                            </div>
                            <div class="form-group">
                                <label for="address">Confirm Password</label>
                                <input type="password" class="form-control" id="password_confirm" name="password_confirmation">
                            </div>

                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.user.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title','Edit User')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-body">
                <h4 class="card-title">Update User</h4>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form action="{{route('admin.user.update',$user->id)}}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{$user->name}}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{$user->email}}">
                            </div>

                            <div class="form-group">
                                <label for="role">Role</label>
                                <select class="select2 form-control" name="role">
                                    @foreach($roles as $role)
                                        <option value="{{$role->id}}" {{$role->id == $user->role_id ? 'selected' : ''}}>{{$role->title}}</option>
                                    @endforeach
                                </select>
                            </div>



                            <div class="form-group">
                                <label for="phone">Password</label>
                                <input type="password" class="form-control" id="phone" name="password">
                            </div>
                            <div class="form-group">
                                <label for="address">Confirm Password</label>
                                <input type="password" class="form-control" id="password_confirm" name="password_confirmation">
                            </div>

                            <button type="submit" class="btn btn-success m-r-10">Submit</button>
                            <a href="{{route('admin.user.index')}}" class="btn btn-dark">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('title','Users')

@push('css')

    <link href="{{asset('backend/'.'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">

@endpush


@section('content')
    <a href="{{route('admin.user.create')}}" class="btn btn-primary btn-success">Add User</a>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">All Users</h4>
                    <h6 class="card-subtitle"></h6>
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped table-bordered" width="100%">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Added ON</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{$user->id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->Role->title}}</td>
                                    <td>{{$user->created_at}}</td>
                                    <td>
                                        <a href="{{route('admin.user.edit',$user->id)}}"><i class="fas fa-edit"></i></a>
                                        <a href="javascript:void(0)" class="delete-item" data-id="{{$user->id}}"><i class="fa fa-trash"></i> </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@push('script')
    <script src="{{asset('backend/'.'assets/extra-libs/DataTables/datatables.min.js')}}"></script>

    <script>
        $( document ).ready(function() {

            $("#datatable").DataTable({
                "order": [[ 4, "desc" ]],
                "columnDefs": [
                    { "searchable": false, "targets": 4 }
                ]
            })

            $(".delete-item").click(function () {

                let deleteForm = document.createElement('form'),
                    currentURL = `{{route('admin.user.destroy','deleteid')}}`,
                    deleteURL = currentURL.replace('deleteid',this.dataset.id),
                    csrfInput = document.createElement('input'),
                    methodInput = document.createElement('input')
                deleteForm.style.display = 'none';
                deleteForm.method = 'POST'
                deleteForm.action = deleteURL
                csrfInput.name = `_token`
                csrfInput.value = `{{csrf_token()}}`
                methodInput.name = `_method`
                methodInput.value = `DELETE`
                deleteForm.appendChild(csrfInput)
                deleteForm.appendChild(methodInput)
                document.body.appendChild(deleteForm)
                deleteForm.submit()

            })


        })
    </script>
@endpush

resources/views/admin/user/show.blade.php
@extends('layouts.admin')

@section('title','View User')

@push('css')


@endpush


@section('content')
@endsection


@push('script')

@endpush